---
- hosts: localhost
  become: true
  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /home/ansadmin/Devops_case_study

  - name: create tag to image
    command: docker tag simple-devops-image sathishsekhar/simple-devops-image

  - name: Log into DockerHub
    docker_login:
      username: XXXXXXXXX
      password: XXXXXXXXX
      email: sathishkumaran85@gmail.com

  - name: push image on to dockerhub
    command: docker push sathishsekhar/simple-devops-image

  - name: remove docker immages from ansible server
    command: docker rmi simple-devops-image:latest sathishsekhar/simple-devops-image
    ignore_errors: yes
